/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiDocsRouteImport } from './routes/api/docs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as ApiExtensionTrackRouteImport } from './routes/api/extension/track'
import { Route as ApiExtensionSigninRouteImport } from './routes/api/extension/signin'
import { Route as ApiExtensionRefreshRouteImport } from './routes/api/extension/refresh'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications/$applicationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiExtensionTrackRoute = ApiExtensionTrackRouteImport.update({
  id: '/api/extension/track',
  path: '/api/extension/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionSigninRoute = ApiExtensionSigninRouteImport.update({
  id: '/api/extension/signin',
  path: '/api/extension/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionRefreshRoute = ApiExtensionRefreshRouteImport.update({
  id: '/api/extension/refresh',
  path: '/api/extension/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/api/extension/refresh': typeof ApiExtensionRefreshRoute
  '/api/extension/signin': typeof ApiExtensionSigninRoute
  '/api/extension/track': typeof ApiExtensionTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/api/extension/refresh': typeof ApiExtensionRefreshRoute
  '/api/extension/signin': typeof ApiExtensionSigninRoute
  '/api/extension/track': typeof ApiExtensionTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/api/extension/refresh': typeof ApiExtensionRefreshRoute
  '/api/extension/signin': typeof ApiExtensionSigninRoute
  '/api/extension/track': typeof ApiExtensionTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/applications'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/events'
    | '/settings'
    | '/api/docs'
    | '/api/openapi'
    | '/applications/$applicationId'
    | '/api/extension/refresh'
    | '/api/extension/signin'
    | '/api/extension/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/applications'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/events'
    | '/settings'
    | '/api/docs'
    | '/api/openapi'
    | '/applications/$applicationId'
    | '/api/extension/refresh'
    | '/api/extension/signin'
    | '/api/extension/track'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/applications'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/events'
    | '/_authenticated/settings'
    | '/api/docs'
    | '/api/openapi'
    | '/_authenticated/applications/$applicationId'
    | '/api/extension/refresh'
    | '/api/extension/signin'
    | '/api/extension/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  ApiExtensionRefreshRoute: typeof ApiExtensionRefreshRoute
  ApiExtensionSigninRoute: typeof ApiExtensionSigninRoute
  ApiExtensionTrackRoute: typeof ApiExtensionTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/extension/track': {
      id: '/api/extension/track'
      path: '/api/extension/track'
      fullPath: '/api/extension/track'
      preLoaderRoute: typeof ApiExtensionTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/signin': {
      id: '/api/extension/signin'
      path: '/api/extension/signin'
      fullPath: '/api/extension/signin'
      preLoaderRoute: typeof ApiExtensionSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/refresh': {
      id: '/api/extension/refresh'
      path: '/api/extension/refresh'
      fullPath: '/api/extension/refresh'
      preLoaderRoute: typeof ApiExtensionRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsApplicationIdRoute:
      AuthenticatedApplicationsApplicationIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  ApiExtensionRefreshRoute: ApiExtensionRefreshRoute,
  ApiExtensionSigninRoute: ApiExtensionSigninRoute,
  ApiExtensionTrackRoute: ApiExtensionTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
